trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '6.x' # Specify the .NET version you need
    installationPath: $(Agent.ToolsDirectory)/dotnet

- script: dotnet build --configuration Release
  displayName: 'Build Project'

- script: dotnet test --configuration Release --no-build
  displayName: 'Run Tests'
